name: get
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: |
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.zhheo.com/ -o zhheo.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.thyuu.com/ -o thyuu.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://akilar.top/ -o akilar.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.chuckle.top/ -o chuckle.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://anzhiy.cn/ -o anzhiy.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.eurkon.com/ -o eurkon.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.jayhrn.com/ -o jayhrn.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.leonus.cn/ -o leonus.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://dusays.com/ -o dusays.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.tencent-qq.cn/ -o tencent-qq.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://zfe.one/ -o zfe.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.justlovesmile.top/ -o justlovesmile.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://tzy1997.com/ -o tzy1997.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.gmcj0816.top/ -o gmcj0816.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.ohyee.cc/ -o ohyee.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://wiki.eryajf.net/ -o eryajf.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://immmmm.com/ -o immmmm.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.orangex4.cool/ -o orangex4.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://hugo.bnblogs.cc/ -o bnblogs.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.shifeiti.com/ -o shifeiti.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://opeach.cn/ -o opeach.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.acozycotage.net/ -o acozycotage.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.moyuql.top/ -o moyuql.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://taheta.ren/ -o taheta.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.marcus233.top/ -o marcus233.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blogwe.com/ -o blogwe.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.foreverblog.cn/ -o foreverblog.jpg




        curl https://purge.jsdelivr.net/gh/cajunlei/ScreenShot@gh-pages/*.*
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./
